name: Contracts-Build-Test

on:
  push: 
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  cwd: ${{github.workspace}}/contracts

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
          
      - name: Run Unit Test
        run: yarn test
        env:
          RPC_URL_GOERLI: ${{ secrets.RPC_URL_GOERLI }}
          GOERLI_LINK: ${{ secrets.GOERLI_LINK }}
          GOERLI_VRF_WRAPPER: {{ secrets.GOERLI_VRF_WRAPPER }}
          GOERLI_LINK_WHALE: {{ secrets.GOERLI_LINK_WHALE }}
